//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossInventoryApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossInventoryApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CloseAppViewNoButton {
            get {
                return ResourceManager.GetString("CloseAppViewNoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CloseAppViewYesButton {
            get {
                return ResourceManager.GetString("CloseAppViewYesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ListItemsViewItemCancelButton {
            get {
                return ResourceManager.GetString("ListItemsViewItemCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string ListItemsViewItemCodeColHeader {
            get {
                return ResourceManager.GetString("ListItemsViewItemCodeColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string ListItemsViewItemDescriptionColHeader {
            get {
                return ResourceManager.GetString("ListItemsViewItemDescriptionColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string ListItemsViewItemLastUpdateCollHeader {
            get {
                return ResourceManager.GetString("ListItemsViewItemLastUpdateCollHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.ty.
        /// </summary>
        public static string ListItemsViewItemQuantityCollHeader {
            get {
                return ResourceManager.GetString("ListItemsViewItemQuantityCollHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ListItemsViewItemSaveButton {
            get {
                return ResourceManager.GetString("ListItemsViewItemSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MainViewCloseApp {
            get {
                return ResourceManager.GetString("MainViewCloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventoried items.
        /// </summary>
        public static string MainViewInventoriedItems {
            get {
                return ResourceManager.GetString("MainViewInventoriedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string MainViewNewItem {
            get {
                return ResourceManager.GetString("MainViewNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Items.
        /// </summary>
        public static string MainViewSearchItems {
            get {
                return ResourceManager.GetString("MainViewSearchItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cross-platform Inventory app.
        /// </summary>
        public static string MainViewTitle {
            get {
                return ResourceManager.GetString("MainViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual quantity.
        /// </summary>
        public static string NewItemActualQuantity {
            get {
                return ResourceManager.GetString("NewItemActualQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string NewItemCancelButton {
            get {
                return ResourceManager.GetString("NewItemCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code number.
        /// </summary>
        public static string NewItemCodeNumberTextBlock {
            get {
                return ResourceManager.GetString("NewItemCodeNumberTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NewItemDescriptionTextBlock {
            get {
                return ResourceManager.GetString("NewItemDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string NewItemSaveButton {
            get {
                return ResourceManager.GetString("NewItemSaveButton", resourceCulture);
            }
        }
    }
}
